### ISSUE TITLE
stanza version

### ISSUE THREAD

**Issue by Chenhao-Leon** [INK-USC/shifted-label-distribution#6]
Hi, I am running into some problems. I wanna know which stanza version do you use. Thanks

**Comment by Chenhao-Leon** [comment]
my version is 0.3 . Here are errors
`python2 DataProcessor/feature_generation.py NYT 5 0 1.0 1

Start nlp parsing
Process Process-1:
Traceback (most recent call last):
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 42, in parse
    parser = NLPParser()
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 23, in __init__
    self.parser = CoreNLPClient(default_annotators=['ssplit', 'tokenize', 'pos', 'ner'], server="http://localhost:9000")
  File "/home/ch/.local/lib/python2.7/site-packages/stanza/nlp/corenlp.py", line 47, in __init__
    assert requests.get(self.server).ok, 'Stanford CoreNLP server was not found at location {}'.format(self.server)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2c1f88e210>: Failed to establish a new connection: [Errno 111] Connection refused',))
Process Process-2:
Traceback (most recent call last):
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 42, in parse
    parser = NLPParser()
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 23, in __init__
    self.parser = CoreNLPClient(default_annotators=['ssplit', 'tokenize', 'pos', 'ner'], server="http://localhost:9000")
  File "/home/ch/.local/lib/python2.7/site-packages/stanza/nlp/corenlp.py", line 47, in __init__
    assert requests.get(self.server).ok, 'Stanford CoreNLP server was not found at location {}'.format(self.server)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2c1f88a2d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
Process Process-3:
Traceback (most recent call last):
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 42, in parse
    parser = NLPParser()
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 23, in __init__
    self.parser = CoreNLPClient(default_annotators=['ssplit', 'tokenize', 'pos', 'ner'], server="http://localhost:9000")
  File "/home/ch/.local/lib/python2.7/site-packages/stanza/nlp/corenlp.py", line 47, in __init__
    assert requests.get(self.server).ok, 'Stanford CoreNLP server was not found at location {}'.format(self.server)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2c1f88a390>: Failed to establish a new connection: [Errno 111] Connection refused',))
Process Process-4:
Traceback (most recent call last):
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 42, in parse
    parser = NLPParser()
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 23, in __init__
    self.parser = CoreNLPClient(default_annotators=['ssplit', 'tokenize', 'pos', 'ner'], server="http://localhost:9000")
  File "/home/ch/.local/lib/python2.7/site-packages/stanza/nlp/corenlp.py", line 47, in __init__
    assert requests.get(self.server).ok, 'Stanford CoreNLP server was not found at location {}'.format(self.server)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2c1f887450>: Failed to establish a new connection: [Errno 111] Connection refused',))
Process Process-5:
Traceback (most recent call last):
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 42, in parse
    parser = NLPParser()
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 23, in __init__
    self.parser = CoreNLPClient(default_annotators=['ssplit', 'tokenize', 'pos', 'ner'], server="http://localhost:9000")
  File "/home/ch/.local/lib/python2.7/site-packages/stanza/nlp/corenlp.py", line 47, in __init__
    assert requests.get(self.server).ok, 'Stanford CoreNLP server was not found at location {}'.format(self.server)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2c1f887510>: Failed to establish a new connection: [Errno 111] Connection refused',))
Train set parsing done
Process Process-6:
Traceback (most recent call last):
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 42, in parse
    parser = NLPParser()
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 23, in __init__
    self.parser = CoreNLPClient(default_annotators=['ssplit', 'tokenize', 'pos', 'ner'], server="http://localhost:9000")
  File "/home/ch/.local/lib/python2.7/site-packages/stanza/nlp/corenlp.py", line 47, in __init__
    assert requests.get(self.server).ok, 'Stanford CoreNLP server was not found at location {}'.format(self.server)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2c1fe4e210>: Failed to establish a new connection: [Errno 111] Connection refused',))
Process Process-7:
Traceback (most recent call last):
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 42, in parse
    parser = NLPParser()
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 23, in __init__
    self.parser = CoreNLPClient(default_annotators=['ssplit', 'tokenize', 'pos', 'ner'], server="http://localhost:9000")
  File "/home/ch/.local/lib/python2.7/site-packages/stanza/nlp/corenlp.py", line 47, in __init__
    assert requests.get(self.server).ok, 'Stanford CoreNLP server was not found at location {}'.format(self.server)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2c1fe492d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
Process Process-8:
Traceback (most recent call last):
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 42, in parse
    parser = NLPParser()
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 23, in __init__
    self.parser = CoreNLPClient(default_annotators=['ssplit', 'tokenize', 'pos', 'ner'], server="http://localhost:9000")
  File "/home/ch/.local/lib/python2.7/site-packages/stanza/nlp/corenlp.py", line 47, in __init__
    assert requests.get(self.server).ok, 'Stanford CoreNLP server was not found at location {}'.format(self.server)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2c1fe48390>: Failed to establish a new connection: [Errno 111] Connection refused',))
Process Process-9:
Traceback (most recent call last):
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 42, in parse
    parser = NLPParser()
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 23, in __init__
    self.parser = CoreNLPClient(default_annotators=['ssplit', 'tokenize', 'pos', 'ner'], server="http://localhost:9000")
  File "/home/ch/.local/lib/python2.7/site-packages/stanza/nlp/corenlp.py", line 47, in __init__
    assert requests.get(self.server).ok, 'Stanford CoreNLP server was not found at location {}'.format(self.server)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2c1fe46450>: Failed to establish a new connection: [Errno 111] Connection refused',))
Process Process-10:
Traceback (most recent call last):
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 42, in parse
    parser = NLPParser()
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 23, in __init__
    self.parser = CoreNLPClient(default_annotators=['ssplit', 'tokenize', 'pos', 'ner'], server="http://localhost:9000")
  File "/home/ch/.local/lib/python2.7/site-packages/stanza/nlp/corenlp.py", line 47, in __init__
    assert requests.get(self.server).ok, 'Stanford CoreNLP server was not found at location {}'.format(self.server)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2c1fe46510>: Failed to establish a new connection: [Errno 111] Connection refused',))
Dev set parsing done
Process Process-11:
Traceback (most recent call last):
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 42, in parse
    parser = NLPParser()
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 23, in __init__
    self.parser = CoreNLPClient(default_annotators=['ssplit', 'tokenize', 'pos', 'ner'], server="http://localhost:9000")
  File "/home/ch/.local/lib/python2.7/site-packages/stanza/nlp/corenlp.py", line 47, in __init__
    assert requests.get(self.server).ok, 'Stanford CoreNLP server was not found at location {}'.format(self.server)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2c1f85e210>: Failed to establish a new connection: [Errno 111] Connection refused',))
Process Process-12:
Traceback (most recent call last):
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 42, in parse
    parser = NLPParser()
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 23, in __init__
    self.parser = CoreNLPClient(default_annotators=['ssplit', 'tokenize', 'pos', 'ner'], server="http://localhost:9000")
  File "/home/ch/.local/lib/python2.7/site-packages/stanza/nlp/corenlp.py", line 47, in __init__
    assert requests.get(self.server).ok, 'Stanford CoreNLP server was not found at location {}'.format(self.server)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2c1f8592d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
Process Process-14:
Traceback (most recent call last):
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 42, in parse
    parser = NLPParser()
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 23, in __init__
    self.parser = CoreNLPClient(default_annotators=['ssplit', 'tokenize', 'pos', 'ner'], server="http://localhost:9000")
  File "/home/ch/.local/lib/python2.7/site-packages/stanza/nlp/corenlp.py", line 47, in __init__
    assert requests.get(self.server).ok, 'Stanford CoreNLP server was not found at location {}'.format(self.server)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2c1f857450>: Failed to establish a new connection: [Errno 111] Connection refused',))
Process Process-13:
Traceback (most recent call last):
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 42, in parse
    parser = NLPParser()
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 23, in __init__
    self.parser = CoreNLPClient(default_annotators=['ssplit', 'tokenize', 'pos', 'ner'], server="http://localhost:9000")
  File "/home/ch/.local/lib/python2.7/site-packages/stanza/nlp/corenlp.py", line 47, in __init__
    assert requests.get(self.server).ok, 'Stanford CoreNLP server was not found at location {}'.format(self.server)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 542, in request
Process Process-15:
    resp = self.send(prep, **send_kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
Traceback (most recent call last):
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2c1f859390>: Failed to establish a new connection: [Errno 111] Connection refused',))
    self.run()
  File "/home/ch/anaconda3/envs/shifted-neural2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 42, in parse
    parser = NLPParser()
  File "/home/ch/experiment/shifted-label-distribution/DataProcessor/nlp_parse.py", line 23, in __init__
    self.parser = CoreNLPClient(default_annotators=['ssplit', 'tokenize', 'pos', 'ner'], server="http://localhost:9000")
  File "/home/ch/.local/lib/python2.7/site-packages/stanza/nlp/corenlp.py", line 47, in __init__
    assert requests.get(self.server).ok, 'Stanford CoreNLP server was not found at location {}'.format(self.server)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/home/ch/.local/lib/python2.7/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=9000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f2c1f857510>: Failed to establish a new connection: [Errno 111] Connection refused',))
Test set parsing done
Start em feature extraction
start train feature generation


mention :0
feature :0
label :0
Feature after filter: 0
start test feature generation


start test feature generation


Start em training and test data generation
0
start test
0
start dev
0
start mention part
start feature_type part
Start rm feature extraction
start train feature generation


mention :0
feature :0
label :0
Feature after filter: 0
start test feature generation


start test feature generation


Start rm training and test data generation
0
start test
0
start dev
0
start mention part
start feature_type part`

**Comment by TarunTater** [comment]
@Chenhao-Leon - how did you fix this error ?
